# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-nanobind.spec

update_release: false

# add or remove files that should be synced
files_to_sync:
    - python-nanobind.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: nanobind
# downstream (Fedora) RPM package name
downstream_package_name: python-nanobind

upstream_project_url: https://github.com/wjakob/nanobind
issue_repository: https://github.com/kwk/python-nanobind

srpm_build_deps:
  - python3-build

jobs:
# Run build for all PRs that target the main branch
- job: copr_build
  trigger: pull_request
  branch: main
  targets:
    - fedora-all

# Run build for all pushes to main
- job: copr_build
  trigger: commit
  branch: main
  owner: "kkleine"
  project: python-nanobind
  targets:
    - fedora-all
  list_on_homepage: True
